# Logistische Regression

:::{.callout-tip}
### Quelle
@festlscharkow2013
:::

## Pakete und Daten laden

```{r, include = F}
library(lme4)
library(marginaleffects)
library(report)
library(tidyverse)
theme_set(theme_minimal())
```

```{r}
festl13 <- haven::read_sav("data/Festl13.sav") %>%
  mutate(gender = as_factor(gender))
festl13
```

### Häufigkeiten und Chi-Quadrat Test

```{r}
table(festl13$cbvictim_gen, festl13$gender)

table(festl13$cbvictim_gen, festl13$gender) %>%
  chisq.test()
```

### Bivariate logistische Regression

```{r}
m1 <- glm(cbvictim_gen ~ gender, festl13, family = binomial(link = "logit"))
```

### Unstandardisierte B

```{r}
report::report_table(m1)
```

### Exp(B) bzw. Odds Ratios

```{r}
report::report_table(m1, exponentiate = TRUE)
```

### Pseudo R-Quadrate

```{r}
performance::r2_mcfadden(m1)
performance::r2_nagelkerke(m1)
performance::r2_coxsnell(m1)
```

### Intercept umrechnen

```{r}
coef(m1)

coef(m1)[1] %>%
  plogis()
```

### Average Marginal Effects

```{r}
marginaleffects::avg_comparisons(m1)
```

### Vorhergesagte Wahrscheinlichkeiten

```{r}
marginaleffects::avg_predictions(m1, variables = "internetuse")
```

### Visualisiert

```{r}
marginaleffects::avg_predictions(m1, variables = "gender") %>%
  ggplot(aes(x = gender, y = estimate, ymin = conf.low, ymax = conf.high)) +
  geom_pointrange() +
  labs(y = "Predicted Probability", x = "Gender")
```

